from enum import Enum


class Mode(Enum):
    CLI = "cli"
    SERVICE = "service"


DEFAULT_BOOTSTRAP_SERVER = "localhost:9092"
DEFAULT_CAPTURE_DIR = "/tmp/kafka-collector"
DEFAULT_PORT = 8080
DEFAULT_MODE = Mode.CLI

ENV_TOPICS = "KAFKA_TOPICS"
ENV_BOOTSTRAP_SERVER = "KAFKA_BOOTSTRAP_SERVER"
ENV_GROUP = "KAFKA_GROUP"
ENV_CAPTURE_DIR = "COLLECTOR_CAPTURE_DIR"
ENV_MODE = "COLLECTOR_MODE"
ENV_SERVICE_PORT = "COLLECTOR_SERVICE_PORT"

KAFKA_AUTO_OFFSET_RESET = "latest"
KAFKA_ENABLE_AUTO_COMMIT = True
KAFKA_POLL_TIMEOUT_MS = 100
